image: ubuntu
platform: Any CPU

environment:
  CODACY_PROJECT_TOKEN:
    secure: yQLuhdsM6C2S/7BsNTbuXMuhmnJSCuTiFAFIBqPh34Fu1LZENgUSsznCIOVmNYf1
  CC_TEST_REPORTER_ID:
    secure: VnEB7IrjwjhhmYaiCeqD9jhajxNkaCS2EWJSaC/W/PXdLULRR9aEBNRd11qILbPynXv1IDpl51PA/lV4Jk/Pcd4AJGheJF5/nz0D39Dn7Zs=

stack: "node 14"

install:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - sh: npm ci
  - sh: npm install -g mocha nyc

before_test:
  # Download codeclimate test report
  - sh: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
  - sh: chmod +x ./codeclimate-test-reporter

test_script:
  - nyc --reporter=lcov mocha --timeout 30000

after_test:
  # Send test result to codeclimate
  - sh: ./codeclimate-test-reporter before-build
  - sh: ./codeclimate-test-reporter after-build -t lcov --exit-code $?
  # Send test result to Codacy
  - sh: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

# Don't actually build.
build: off
