export declare const months: string[];
export declare const days: string[];
export declare function dateToInteger(dateObj: Date): number;
export declare function dateToString(dateObj: Date): string;
export declare function dateIntegerToString(dateInteger: number): string;
export declare function dateStringToDate(dateString: string): Date;
export declare function dateStringToInteger(dateString: string): number;
export declare function dateDifferenceInDays(fromDateObj: Date, toDateObj: Date): number;
export declare function dateStringDifferenceInDays(fromDateString: string, toDateString: string): number;
export declare function dateToTimeInteger(dateObj: Date): number;
export declare function dateToTimeString(dateObj: Date): string;
export declare function timeIntegerToString(timeInteger: number): string;
export declare function timeStringToInteger(timeString: string): number;
