export declare const months: string[];
export declare const days: string[];
export declare const dateToInteger: (dateObject: Date) => number;
export declare const dateToString: (dateObject: Date) => string;
export declare function dateIntegerToString(dateInteger: number): string;
export declare function dateIntegerToDate(dateInteger: number): Date;
export declare const dateStringToDate: (dateString: string) => Date;
export declare const dateStringToInteger: (dateString: string) => number;
export declare const dateDifferenceInDays: (fromDateObject: Date, toDateObject: Date) => number;
export declare const dateStringDifferenceInDays: (fromDateString: string, toDateString: string) => number;
export declare const dateToTimeInteger: (dateObject: Date) => number;
export declare const dateToTimeString: (dateObject: Date) => string;
export declare const timeIntegerToString: (timeInteger: number) => string;
export declare const timeStringToInteger: (timeString: string) => number;
